cities = ['Tianjin', 'Beijing', 'Shenzhen', 'Guangzhou', 'Chengdu', 'Qingdao']
print(cities)
print(cities[0])
print(cities[1])
print(cities[2])
print(cities[3])
print(cities[4])
print(cities[5])
print(cities[-1])
print(cities[0].title())
cities[0] = 'Binhai'
print(cities)
cities.append('Tianjin')
print(cities)
cities.insert(0, 'Tangshan')
print(cities)
del cities[0]
print(cities)
print(cities.pop())
print(cities)
print(cities.pop(0))
print(cities)
cities.remove('Beijing')
print(cities)
print(sorted(cities))
print(cities)
cities.reverse()
print(cities)
cities.reverse()
print(cities)
cities.sort()
print(cities)
cities.sort(reverse=True)
print(cities)